from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
REPORTS_DIR = BASE_DIR / "reports"


def safe(value):
    value = "" if value is None else str(value)
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )


def li(items):
    return "\n".join(f"<li>{safe(item)}</li>" for item in items)


def generate_report_html(report_id, email_data, result):
    REPORTS_DIR.mkdir(exist_ok=True)
    file_path = REPORTS_DIR / f"incident_report_{report_id}.html"
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Incident Report #{report_id}</title>
<style>
body {{ font-family: Arial, sans-serif; background: #f4f7fb; color: #1f2937; margin: 0; padding: 32px; }}
.report {{ max-width: 900px; margin: auto; background: white; padding: 34px; border-radius: 18px; box-shadow: 0 12px 35px rgba(15,23,42,.12); }}
h1 {{ margin-top: 0; color: #0f172a; }}
.meta {{ color: #64748b; margin-bottom: 24px; }}
.grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin: 20px 0; }}
.card {{ border: 1px solid #e5e7eb; border-radius: 14px; padding: 16px; background: #f8fafc; }}
.label {{ font-size: 12px; text-transform: uppercase; letter-spacing: .08em; color: #64748b; }}
.value {{ font-size: 18px; font-weight: 700; margin-top: 6px; }}
.badge {{ display: inline-block; padding: 7px 12px; border-radius: 999px; font-weight: 700; }}
.Low {{ background: #dcfce7; color: #166534; }}
.Medium {{ background: #fef9c3; color: #854d0e; }}
.High {{ background: #ffedd5; color: #9a3412; }}
.Critical {{ background: #fee2e2; color: #991b1b; }}
pre {{ white-space: pre-wrap; background: #0f172a; color: #e2e8f0; padding: 18px; border-radius: 14px; }}
section {{ margin-top: 26px; }}
li {{ margin: 8px 0; }}
.footer {{ margin-top: 30px; font-size: 13px; color: #64748b; border-top: 1px solid #e5e7eb; padding-top: 16px; }}
@media print {{ body {{ background:white; padding:0; }} .report {{ box-shadow:none; border-radius:0; }} }}
</style>
</head>
<body>
<div class="report">
<h1>Phishing Email Incident Report</h1>
<p class="meta">Report ID: #{report_id}</p>
<div class="grid">
<div class="card"><div class="label">Risk Level</div><div class="value"><span class="badge {safe(result['risk_level'])}">{safe(result['risk_level'])}</span></div></div>
<div class="card"><div class="label">Phishing Score</div><div class="value">{safe(result['phishing_score'])}/100</div></div>
<div class="card"><div class="label">Confidence</div><div class="value">{safe(result['confidence'])}</div></div>
<div class="card"><div class="label">Sender</div><div class="value">{safe(email_data.get('sender_email'))}</div></div>
</div>
<section><h2>Email Details</h2><p><strong>Subject:</strong> {safe(email_data.get('subject'))}</p><p><strong>Links:</strong> {safe(email_data.get('links')) or 'N/A'}</p><p><strong>Attachment:</strong> {safe(email_data.get('attachment_name')) or 'N/A'}</p></section>
<section><h2>Submitted Email Body</h2><pre>{safe(email_data.get('email_body'))}</pre></section>
<section><h2>Detected Indicators</h2><ul>{li(result.get('detected_indicators', []))}</ul></section>
<section><h2>AI Analysis Explanation</h2><p>{safe(result.get('explanation'))}</p></section>
<section><h2>Recommended Actions</h2><ul>{li(result.get('recommended_actions', []))}</ul></section>
<div class="footer">This report is generated by AI-Powered Phishing Email Analyzer. It supports security review but does not replace expert investigation.</div>
</div>
</body>
</html>
"""
    file_path.write_text(html, encoding="utf-8")
    return file_path
